print("Hello")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe ")
print(" hola bebe que fue no que muy tragadita ")
print("todos los dias")